name: Déplacer les fichiers JSON vers files/

on:
  push:
    paths:
      - "json/*.json"

jobs:
  move-json:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v3

      - name: Déplacer les fichiers JSON vers files/
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          for file in json/*.json; do
            filename=$(basename "$file")
            content=$(base64 -w 0 "$file")
            json="{\"message\": \"Déplacement de $filename\", \"content\": \"$content\"}"
            curl -X PUT -H "Authorization: token $GH_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -d "$json" \
                 "https://api.github.com/repos/${{ github.repository }}/contents/files/$filename"
          done
